### ISSUE TITLE
On click it should open in new tab

### ISSUE THREAD

**Issue by ferminrp** [1Feed/browser-extension#1]
It has happened in the past that I'm in the middle of a great article and want to make sure I add this source to my feeds. Hitting on the extension automatically redirects me to 1feed which is cool, but I'd rather have this opened in a new tab instead of the current one so I don't miss where I was reading.

**Comment by Booligoosh** [comment]
Moved this over to the extension repo itself! (the extension itself is open-source as it's pretty minimal and I want people to be able to trust something that they're adding to their browser)

**Comment by Booligoosh** [comment]
This should ship as soon as it has been reviewed by Mozilla Addons / Chrome Webstore!

Also, the next 1Feed release will ship with some nice improvements to the Add page, making it load much faster and not automatically going to your 1Feed once the feed has been added:

<img width="1514" alt="Screen Shot 2021-08-25 at 8 27 24 pm" src="https://user-images.githubusercontent.com/14034891/130774477-0db301ad-e513-4e0d-bb5a-35b5d1245635.png">

**Comment by ferminrp** [comment]
Super glad to see you back =)
